services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - meow-net

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+08:00
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "meow_user", "-p666"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meow-net

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: meow_user
      CLICKHOUSE_PASSWORD: "666"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - meow-net
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

networks:
  meow-net:
    driver: bridge

volumes:
  mysql_data:
  clickhouse_data:
  redis_data: